### ISSUE TITLE
Jupyter notebook problems

### ISSUE THREAD

**Issue by bdch1234** [IntelPython/hpat#86]
I can't seem to get mpi to work in jupyter notebook. Followed install instructions and enabled in IPython Clusters, but I still get same result as without mpiexec. It does however work when running from command line. The file hpat_test.py contains the pi-example:
`
$ python hpat_test.py
Execution time: 2.0605809688568115
result: 3.14172644
`
`
$ mpiexec -n=4 python hpat_test.py
Execution time: 0.9896800518035889
result: 3.14176146
`
In a notebook:
`Execution time: 2.080565929412842 
result: 3.14158518`

I am running this from Ubuntu running on windows subsystem for linux, is it related to that?

**Comment by DrTodd13** [comment]
The short answer is that HPAT won't distribute work via MPI in Jupyter yet but we are working on it.  We can't mpiexec the whole of Jupyter so we have to integrate HPAT with ipyparallel to distribute the work and there are several issues that have to be solved there.

**Comment by bdch1234** [comment]
Thanks for confirming.
